### ISSUE TITLE
Application Details PAGE

### ISSUE THREAD

**Issue by pragalli** [BootNodeDev/allo-protocol-graph#24]

**Comment by marcelorubini** [comment]
@InakyMaister please find below RoundApplications view displaying details for both DirectGrant and QuadraticFunding rounds

[DIRECT GRANT](https://gitcoin-dr-builder.app/chains/5/rounds/0x2d5f4247481ca31073ad55c6dbbb6db047d51b07/view/bafkreibpgafzua5xi5g5p3votsok75vuhvrr3da6nz4vxpxztu3ngze6yu)
![Screenshot from 2023-08-02 18-08-36](https://github.com/BootNodeDev/allo-protocol-graph/assets/2502507/70c0b0d6-870f-4127-86e2-cec86100072f)

[QUADRATIC FUNDING](https://gitcoin-dr-builder.app/chains/5/rounds/0x749e32422f8572b0c72ad71b3834309e7c93bd2b/view/bafkreicztyext3koztby3hpejiyiqcma7kutw4vmdwz4t27cvvqnroiy4i)
![Screenshot from 2023-08-02 18-09-33](https://github.com/BootNodeDev/allo-protocol-graph/assets/2502507/ad0708e1-0483-43c1-91d2-24dad2b595a6)
