### ISSUE TITLE
Individual Milestones for Applications Design

### ISSUE THREAD

**Issue by tloffler** [BootNodeDev/allo-protocol-graph#34]
UI/UX #30

As a Builder:
I want to be able to add Milestones as individual items on my application, so they can be edited or deleted easily. This would be similar to the Requirements functionality when a Round is created. If user clicks add new, a new input is displayed so user can complete the new milestone.

As a Round Manager:
I want to be able to mark the Milestone that is being paid when a Payout is done, and see previous milestones that have been already paid.

**Comment by tloffler** [comment]
### Builder
**Listing Milestones as individual items:**
https://www.figma.com/proto/rax6pBts8JLgCh1E58pqf7/Gitcoin?page-id=481%3A2934&type=design&node-id=906-4873&viewport=-9280%2C-8336%2C0.72&t=vue3dHR5tODxiZVL-1&scaling=min-zoom&starting-point-node-id=906%3A5004&mode=design

**Editing Milestones as individual items:**
You can add milestones by clicking on the "add milestone" button.
Once a milestone is added you can remove it by clicking on the "X" button.
https://www.figma.com/proto/rax6pBts8JLgCh1E58pqf7/Gitcoin?page-id=481%3A2934&type=design&node-id=906-5004&viewport=-9280%2C-8336%2C0.72&t=vue3dHR5tODxiZVL-1&scaling=min-zoom&starting-point-node-id=906%3A5004&mode=design

### Manager
**Add multiple Milestones in the application questions list:**
https://www.figma.com/proto/rax6pBts8JLgCh1E58pqf7/Gitcoin?page-id=481%3A2934&type=design&node-id=906-5428&viewport=-9280%2C-8336%2C0.72&t=vue3dHR5tODxiZVL-1&scaling=min-zoom&starting-point-node-id=906%3A5004&mode=design

**List milestones on the project page:**
You can make a new payment by clicking the "New Payment" button. A popup comes up with the payout form where you can select the milestones involved in the amount.
https://www.figma.com/proto/rax6pBts8JLgCh1E58pqf7/Gitcoin?page-id=481%3A2934&type=design&node-id=906-5834&viewport=-9280%2C-8336%2C0.72&t=vue3dHR5tODxiZVL-1&scaling=min-zoom&starting-point-node-id=906%3A5004&mode=design

Once the payment is made on the project page you can see the milestone that was paid
https://www.figma.com/proto/rax6pBts8JLgCh1E58pqf7/Gitcoin?page-id=481%3A2934&type=design&node-id=906-5988&viewport=-9280%2C-8336%2C0.72&t=vue3dHR5tODxiZVL-1&scaling=min-zoom&starting-point-node-id=906%3A5004&mode=design

@jose-garrofe I couldn't add the milestones paid in each payout because it was too much information. Do you think it is necessary?

**Comment by jose-garrofe** [comment]
This looks great @tloffler . No, I don't think it is absolutely necessary to list which milestone was paid on each payment.
