### ISSUE TITLE
Round Stats

### ISSUE THREAD

**Issue by jose-garrofe** [BootNodeDev/allo-protocol-graph#37]
We need to adapt the Round Stats page to only display Direct Round information.
We either decide to reuse this to show other information, or we remove it entirely, since none of the information currently displays applies for Direct Round.

![image.png](https://images.zenhubusercontent.com/61bc9d4eea7b03e431932ef8/0f219569-ed3d-4ac0-9ac3-60236bf9fbcd)

**Comment by marcelorubini** [comment]
@jose-garrofe @pragalli what information from the Round should we show at this section? Are they already defined?

**Comment by jose-garrofe** [comment]
Not yet. We should hide the tab for the moment. Then we can decide if we can use it for any further information needed. (SLA info, for example).
