### ISSUE TITLE
Allow Projects to apply more than once for the same Direct Round.

### ISSUE THREAD

**Issue by jose-garrofe** [BootNodeDev/allo-protocol-graph#43]
Description:
As a Project I want to be able to apply more then once to the same Direct Round.
We need to remove the current restriction that prevents users to apply to the same round with the same project but only for Direct Rounds.
We also need to remove the notification message that alerts the user about not being able to apply again when they're applying to a Direct Round.
![image.png](https://images.zenhubusercontent.com/61bc9d4eea7b03e431932ef8/11f4f16b-c40a-4584-835a-1366c9e83674)
![image.png](https://images.zenhubusercontent.com/61bc9d4eea7b03e431932ef8/d89863a1-0435-4317-8e37-c3f1c98c4c1f)

**Comment by marcelorubini** [comment]
Already fixed, will be merged with now Projects can apply more than once to a Direct Round.
![Screenshot from 2023-07-13 09-29-47](https://github.com/BootNodeDev/allo-protocol-graph/assets/2502507/69a8d232-aac6-48f7-b7bc-bde295f3f29a)

![Screenshot from 2023-07-13 11-35-28](https://github.com/BootNodeDev/allo-protocol-graph/assets/2502507/9e82e9e8-3462-4b80-8c78-5b96c11ef4cb)

@jose-garrofe Not sure if this behavior implies other validations for the RoundApplication to be created such as milestones overlaping.
