### ISSUE TITLE
End an Open Round

### ISSUE THREAD

**Issue by tloffler** [BootNodeDev/allo-protocol-graph#44]
UI/UI #35
Description:
As a Round Manager I want to able to close an Open Round (created without an End Date).
We need to add an option to the Round Detail (button) labeled End Round. This option should only be displayed if the Round does NOT have an End Date.
If Round Manager clicks on the button and confirms the action, the Round will change to Inactive status effectively, and no more projects will be able to apply to the round.
If there are applications in any status other than Approved or Rejected, system should alert the Round Manager about this when they click the End Round button.

**Comment by tloffler** [comment]
-The possibility of setting an End Date for a Direct Round that didn't have an end date was added.

https://www.figma.com/proto/rax6pBts8JLgCh1E58pqf7/Gitcoin?page-id=35%3A220&type=design&node-id=987-5430&viewport=281%2C-562%2C0.21&t=qAEx5FDTs2KAEYau-1&scaling=min-zoom&starting-point-node-id=64%3A635&mode=design

**Comment by jose-garrofe** [comment]
@tloffler Tomas, I think we can avoid the End Round button now that we noticed we have the Round Settings page.
My suggestion is:
If user wants to end the round, they can uncheck the checkbox below the
