### ISSUE TITLE
Explorer - Only display Approved projects on the Round Page.

### ISSUE THREAD

**Issue by jose-garrofe** [BootNodeDev/allo-protocol-graph#45]
Description:
For Quadratic Funding the "All Projects" section displays projects that have already applied for the Round.
We need to change this for Direct Grants. The label should be "Approved Projects" instead of "All Projects", and only approved projects should be displayed here. Projects on Received, In Review, or Rejected status should not be displayed.

![image.png](https://images.zenhubusercontent.com/61bc9d4eea7b03e431932ef8/531da738-2e05-40d0-a7dd-61678fab7830)

**Comment by marcelorubini** [comment]
vercel build for testing: https://grants-stack-builder-git-20-apply-for-directgra-01bffe-bootnode.vercel.app/
will be merged with [PR#37](https://github.com/BootNodeDev/grants-stack/pull/37)

EXPLORER
Replaces _All Projects_ with _Approved Projects_ for DirectGrant Rounds and displays only approved ones.
![Screenshot from 2023-07-17 15-42-50](https://github.com/BootNodeDev/allo-protocol-graph/assets/2502507/e3e78c51-5c41-4ed3-94a3-dc53549ca23b)

![Screenshot from 2023-07-17 15-43-03](https://github.com/BootNodeDev/allo-protocol-graph/assets/2502507/353f0e57-31fa-43fc-95f1-4a47cba55a3c)

QuadraticFunding Rounds remains the same
![Screenshot from 2023-07-17 15-43-10](https://github.com/BootNodeDev/allo-protocol-graph/assets/2502507/698047ad-338e-42eb-a139-a649fc644c6d)
