### ISSUE TITLE
Round Manager - Add Application Detail to the Direct Round form.

### ISSUE THREAD

**Issue by jose-garrofe** [BootNodeDev/allo-protocol-graph#46]
Description:
When creating a Direct Round, the Application Detail question should be included by default.
This should be a paragraph type question, required and non editable.

**Comment by tloffler** [comment]
UI/UX:
@jose-garrofe Application detail input was added to the manager as a paragraph-type question, required and non-editable

https://www.figma.com/proto/rax6pBts8JLgCh1E58pqf7/Gitcoin?page-id=35%3A220&type=design&node-id=60-535&viewport=-1546%2C-6681%2C0.7&t=hj9ENqLOVAxJWQag-1&scaling=min-zoom&starting-point-node-id=35%3A221&mode=design

Also in the project application view:
https://www.figma.com/proto/rax6pBts8JLgCh1E58pqf7/Gitcoin?page-id=35%3A220&type=design&node-id=275-1664&viewport=-1546%2C-6681%2C0.7&t=hj9ENqLOVAxJWQag-1&scaling=min-zoom&starting-point-node-id=64%3A635&show-proto-sidebar=1&mode=design
