### ISSUE TITLE
Round Details - Few small UI bugs.

### ISSUE THREAD

**Issue by jose-garrofe** [BootNodeDev/allo-protocol-graph#49]
![image.png](https://images.zenhubusercontent.com/61bc9d4eea7b03e431932ef8/fc783bb6-8536-4eab-b487-208a5220c289)

- [x] On the breadcrumbs at the top of the page, the Round Details one always has a @ at the start. We need to remove it.
- [x] When the round is an Open Round, the label is "No end time" when it should be " No end date (open round)"

![image.png](https://images.zenhubusercontent.com/61bc9d4eea7b03e431932ef8/b952b07e-ebe3-49f6-89b4-8eb11e5905cb)

- [x] For Quadratic Funding rounds, the application and round dates are too close together. I think we should keep the view that was used before (time below date for each value, see image below).

![image.png](https://images.zenhubusercontent.com/61bc9d4eea7b03e431932ef8/5d73279e-b596-4e09-9ce3-f2da04e515d9)

**Comment by nicosampler** [comment]
Adding @tloffler to help me out with the CSS part.
Let's work on this feedback on `branch direct-grant-round-in-review`

**Comment by tloffler** [comment]
@jose-garrofe Three issues were resolved in the [direct-grant-round-in-review](https://github.com/BootNodeDev/grants-stack/tree/direct-grant-round-in-review) branch

**Comment by jose-garrofe** [comment]
@tloffler a few things missing:
'No end time' should be 'No end date' (Both on the Round List and the Round Details page)
![image.png](https://images.zenhubusercontent.com/61bc9d4eea7b03e431932ef8/2235504f-6506-4448-9e47-e3f45372c198)

Remove the @ at the breadcrumbs before the Round Details text.
![image.png](https://images.zenhubusercontent.com/61bc9d4eea7b03e431932ef8/5365c420-b7d9-4a36-b1c0-4732fb75c6ab)
