### ISSUE TITLE
Builder - Payout Wallet Address field duplicated

### ISSUE THREAD

**Issue by jose-garrofe** [BootNodeDev/allo-protocol-graph#50]
Both for QF and DG forms, the payout wallet address field is duplicated:

![image.png](https://images.zenhubusercontent.com/61bc9d4eea7b03e431932ef8/5a3df9ff-8f52-44c4-bac6-b6dec20ab693)

**Comment by nicosampler** [comment]
@marcelorubini yo hice una modificacion en el manager para q esos campos se envien.  te parece si le sacas el hardcoding en el builder? ya q siempre va a llegar en la metadata.

**Comment by jose-garrofe** [comment]
FYI
This issue also happens for Quadratic Funding application form.
